### PR TITLE
More precise uninitialized plugin

### PR DESCRIPTION
**Pull request by mpflanzer**
The new plugin maintains a defined/undefined value (shadow) for all bits in memory (private, local, global) and in intermediate values. For every instruction a shadow instruction is defined to modify the shadow values accordingly.

Most of the time the shadow values are just propagated through the functions and warnings for undefined values are only emitted under the following conditions:
- they are written to local or global memory
- they are used as arguments to external/unknown functions
- they are needed to determine the control flow

At the moment some of the shadow instructions do not propagate the shadow values with bit-level precision. For them the result is defined if all operands had been defined and undefined otherwise. But they could easily be extended for a more precise handling.

~~Functions for image types and half types are currently still missing. I will add them later on.~~

### CODE REVIEW

**Comment by jrprice** [comment]
I've finally got around to looking at this. I've been running some tests locally, and it seems to work well. Great work!

Are there any outstanding issues or cases where you know this will produce a false-positive/negative?

What's the motivation for producing an error message when an uninitialised value is stored to local memory?

In an ideal world, the error messages that this produces would be able to indicate the original source of the uninitialised value. This may be infeasible however, depending on how much extra data this would need to store.

**Comment by mpflanzer** [comment]
Thanks. There are a few edge cases in which false positives/negatives can get produced:
- The plugin assumes that global memory is initialised after it has been mapped to the host system with write access. This of course need not to be true and can lead to unreported uses of uninitialised values. On the other hand, if this assumption is not made, it would result in a huge amount of false positive warnings for applications that initialise the global memory in the host application.
- A source for false positives is the fairly general handling of the shadow propagation. It is not bit-accurate in most of the cases but instead operates on a per operand basis. So, if an application intentionally uses partially initialised values, e.g. sets and reads only a few bits of a variable and leaves the rest uninitialised, the plugin will still treat the complete value of the variable as uninitialised and is likely to report a false positive warning. This can easily be extended if the shadow functions for certain operations are implemented in a more detailed fashion. However, it might come to the costs of a slower runtime and I think since any kind of bitfields are not permitted in OpenCL the more general implementation will only affect a really small amount of kernels.
- Finally, the image related load and store functions certainly have to be improved. I did not focus on them because I did not need them for my project. They do not actually check the memory allocated by the image but only the image object which is not really correct and might lead to false negatives.

The motivation for error messages at a local memory level was that this also affects kind of a "global" state rather than only the values private to a single work item. Unlike with global memory which can be accessed from outside of the kernel which makes the error reporting necessary, the checks for local memory are not strictly required. But I think there are only a few cases in which uninitialised values in local memory a actually intended. I suppose there are arguments for both options; either to check local memory or to leave it unchecked. I have not measured the performance impact of this particular check but it is comparably low. On the other hand I would not have strong objections against removing the check from the plugin -- at least I cannot think of any at the moment. ;-)

Your last point is about the feature which is called "origin tracking" in the Valgrind and Clang implementations of such a plugin. It is possible but adds a fair amount of overhead in terms of runtime and storage. If it is implemented in the future it should definitely be a optional feature which can be deactivated if not needed. For instance for MemorySanitizer for Clang there is an additional 100% overhead in memory consumption and an additional 2x slowdown on top of the overhead of the "normal" plugin functionality if origin tracking is activated.

**Comment by jrprice** [comment]
OK. I'm not particularly fussed about false negatives at this stage, and I think bit-level accuracy is overkill for now.

I'll leave the local memory check in for now, but since writes to local memory are not visible outside of a single work-group my instinct is that it would better to not report errors at that stage and just keep shadowing until the uninitialised value is used in a branch/call or global memory write.

I experienced some issues when running this plugin with my internal test suite. One of the main issues seemed to be surrounding the deferred initialisation lists (e.g. `m_deferredInit`). Clearing these lists in a  `kernelEnd` callback seemed to fix the issue - does [this commit](https://github.com/jrprice/Oclgrind/commit/744b32f560f8384548d841a185f8cf30a7f0fa2b) look sensible to you?

**Comment by jrprice** [comment]
I found a second issue with per-kernel state persisting across kernel invocations - so I"m also now clearing `ShadowContext::m_globalValues` when each kernel finishes. I also experienced a memory leak which was causing problems when running many kernels back-to-back.

There's fixes for these and one or two other minor issues in the [uninitialized branch](https://github.com/jrprice/Oclgrind/commits/uninitialized) - could you just sanity check these changes to make sure I haven't done anything strange?

I'm just running this through our internal tests one more time with all these fixes - if all is well I'll merge this into master and replace the old plugin with it.

**Comment by mpflanzer** [comment]
Yes, looks good to me. Thanks again for the review and advice during the development!

**Pull request merged**
