### PR TITLE
implement cl_khr_int64_base_atomics & cl_khr_int64_extended_atomics

### LINKED ISSUE #78: Any support for int64 atomics planned?
Hi, this is a really neat project. From looking at CL_DEVICE_EXTENSIONS, I see that the 32 bit int atomic extensions are supported. Are there any plans to support the 64 bit atomics as well (cl_khr_int64_base_atomics)?

### PR DESCRIPTION
**Pull request by petrkalos**
Preview implementation of atom_add.
Before I implement all the methods, do you have any objections?

fixes #78

### CODE REVIEW

**Comment by jrprice** [comment]
The approach looks perfectly reasonable to me.

**Comment by petrkalos** [comment]
I'll try to push the rest of the methods later this week

**Comment by petrkalos** [comment]
Implementation of cl_khr_int64_base_atomics and cl_khr_int64_extended_atomics is now in place.

I've decided to get rid of all the "almost the same" atomic_* implementations and use a templated generic atomic_op<typename T, AtomicOp op> and statically specialise for CmpXcgh, Min/Max, Inc/Dec.

What really remains is the a check for when the extensions are enabled with the "#pragma OPENCL EXTENSION cl_khr_int64_base/extended_atomics : enable"

**Comment by jrprice** [comment]
In general this seems fine, but this has broken the ability to use `atom_*` functions with 32-bit integer types - you seem to be assuming that the `atom_*` functions are only ever 64-bit (which isn't the case). Getting rid of the duplicated code in those atomic functions is nice though.

I'm not sure whether this can be achieved properly with the templated approach that you've opted for, but you could probably do essentially the same thing with a single (non-templated) `atomic_op` function that just checks the overload string for the type.

**Comment by petrkalos** [comment]
> ... but this has broken the ability to use atom_* functions with 32-bit integer types - you seem to be assuming that the atom_* functions are only ever 64-bit (which isn't the case).

I didn't know there are atom_* methods for 32-bit types, could you point me to these in the OpenCL spec?

> I'm not sure whether this can be achieved properly with the templated approach that you've opted for, but you could probably do essentially the same thing with a single (non-templated) atomic_op function that just checks the overload string for the type.

I opted for the templated approach as it will produce static code, hence kind of faster and we also avoiding a lot of branching, but I guess we can create a map<string, AtomicOp> and use this.
I don't mind re-implementing it like that.

**Comment by jrprice** [comment]
> I didn't know there are atom_* methods for 32-bit types, could you point me to these in the OpenCL spec?

They come from the [`cl_khr_int32_base_atomics` extension](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/cl_khr_global_int32_base_atomics.html) for OpenCL 1.0. Although they were renamed to `atomic_*` when they were made core in OpenCL 1.1, the `atom_*` versions are still required to be supported for backwards compatibility.

**Comment by petrkalos** [comment]
Ah apologise for my ignorance, never worker with OpenCL 1.0
I'll implement it in a different style to accommodate this requirement.

Thanks for the feedback

**Comment by jrprice** [comment]
Looks good now, thanks!

**Pull request merged**
