### PR TITLE
[tests] Add binary parameter for createContext

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi James,

Then it is able to use clCreateProgramWithBinary, please review my patch, thanks a lot!

Regards,
Leslie Zhai https://reviews.llvm.org/p/xiangzhai/

### CODE REVIEW

**Comment by jrprice** [comment]
I don't have any particular objection to this, but what's the motivation here? Are you intending to add some tests that use program binaries?

**Comment by xiangzhai** [comment]
Hi James,

Thanks for your response!

> but what's the motivation here? Are you intending to add some tests that use program binaries?

I added tests/apps/cos to test libclc https://github.com/llvm-mirror/libclc/blob/master/test/cos.cl

And I might bought an AMD RX 480 graphic card, so I prefer to test Kernel Binary. but I am investigating the issue: Error during operation 'creating program with binary invalid program binary': -42

```
cl.program = clCreateProgramWithBinary(cl.context, 1, &cl.device,              
                                           &st.st_size, &binary, &status, &err);
```

Is my fault? or libclc issue or simulator?

Regards,
Leslie Zhai

**Comment by jrprice** [comment]
Where does the binary come from? If you're building a binary for a particular architecture (AMD/NVIDIA etc) using libclc, then this definitely won't work with Oclgrind.

Oclgrind doesn't simulate any real architectures, it just emulates OpenCL kernels at the LLVM level. This means that the only kind of binary that Oclgrind can accept is just a plain LLVM bitcode. These internal tests are intended for testing Oclgrind's functionality, not for testing other tools/compilers/libraries etc.

**Comment by xiangzhai** [comment]
Hi James,

Thanks for your kind response.

> These internal tests are intended for testing Oclgrind's functionality, not for testing other tools/compilers/libraries etc.

yes! but how to verify the ELF for AMDGPU target? http://lists.llvm.org/pipermail/llvm-dev/2017-June/114654.html

```
$ llvm-readobj cos.co

File: cos.co
Format: ELF64-amdgpu-hsacobj
Arch: amdgcn
AddressSize: 64bit
```

I might bought an AMD RX 480 graphic card to test it :)

> This means that the only kind of binary that Oclgrind can accept is just a plain LLVM bitcode.

oclgrind libclc/test/cos.ll
Error during operation 'creating program with binary invalid program binary': -42

> Where does the binary come from? If you're building a binary for a particular architecture (AMD/NVIDIA etc) using libclc, then this definitely won't work with Oclgrind.

testcase [cos.cl](https://github.com/llvm-mirror/libclc/blob/master/test/cos.cl)

```
$ clang -Dcl_clang_storage_class_specifiers -isystem /usr/include -include clc/clc.h -target amdgcn--amdhsa -mcpu=carrizo -S -emit-llvm -xcl -o cos.ll cos.cl

$ llvm-link cos.ll /usr/lib/clc/amdgcn--amdhsa.bc -o cos.linked.bc

$ clang -target amdgcn--amdhsa -mcpu=carrizo cos.linked.bc -S -o cos.amdhsa.s

$ clang -x assembler -target amdgcn--amdhsa -mcpu=carrizo -c -o cos.o cos.amdhsa.s

$ clang -target amdgcn--amdhsa cos.o -o cos.co
```

PS: I use [simavr](https://github.com/buserror/simavr) to verify the ELF for AVR target https://reviews.llvm.org/D32991#776611

Regards,
Leslie Zhai

**Comment by jrprice** [comment]
> yes! but how to verify the ELF for AMDGPU target? http://lists.llvm.org/pipermail/llvm-dev/2017-June/114654.html

I'm afraid I can't help you there - this isn't something that Oclgrind is designed to do.

> Error during operation 'creating program with binary invalid program binary': -42

It looks like you are passing the filename to `clCreateProgramWithBinary`, where you should be passing the actual binary data (i.e. the contents of the file). But again, I wouldn't expect this to work with Oclgrind anyway.

**Comment by xiangzhai** [comment]
Hi James,

> But again, I wouldn't expect this to work with Oclgrind anyway.

Never mind, I bought an AMD RX 460 to test the binary :)

Regards,
Leslie Zhai

**Pull request closed without merging**
